- name: this is my 1st playbook
  hosts: all
  tasks:
    - name: print animal name
      debug:
        msg: "Hello I am tiger"
    - name: print another animal
      debug:
        msg: "hello I am Lion"